### ISSUE TITLE
mkpage issues

### ISSUE THREAD

**Issue by adam3smith** [AuthorCarpentry/lesson-template#1]
Hi @tmorrell 
I'm having two problems with mkpage. One might be a set-up issue but I'd appreciate any help, the other one I'm pretty sure is a bug in `mk.website.bash`. This is running on Ubuntu 16.04LTS

1. The bug: On running the script without mkpage installed, I get 

```
Checking necessary software is installed
Generating website
Generating HTML content for .
Rendering ./03-save-export.html
./mk-website.bash: line 24: mkpage: command not found
```
etc. which I think should be impossible given the software check. All the html files come up as empty files.

2. On running the script after installing mkpage, I get the below, which I believe indicates the module is trying to parse YAML as JSON, but I have no idea how to prevent this. Tried with both the latest LTS and the current nodejs version. Output is fort the latter. Any thoughts? And we do have to rely on mkpage? Jekyll, which doesn't even need to run on contributor's computers, is really not an option?

```
Generating website
Generating HTML content for .
Rendering ./03-save-export.html
events.js:163
      throw er; // Unhandled 'error' event
      ^

SyntaxError: Unexpected token . in JSON at position 0
    at JSON.parse (<anonymous>)
    at StreamCaller.transform [as _transform] (/home/sebastian/.nvm/versions/node/v7.10.0/lib/node_modules/mkdoc/node_modules/mkast/lib/parser.js:30:16)
    at StreamCaller.Transform._read (_stream_transform.js:167:10)
    at StreamCaller.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)
    at StreamCaller.Writable.write (_stream_writable.js:241:11)
    at Stream.ondata (_stream_readable.js:557:20)
    at emitOne (events.js:96:13)
    at Stream.emit (events.js:191:7)
```

**Comment by tmorrell** [comment]
@adam3smith I've fixed the AppCheck function to resolve issue 1.

For issue 2, are you rendering the example content in the lesson template?  Could you do mkpage -v and check the version you have installed.  I don't have a problem with rendering the content in the template using mkpage v0.0.16.  

The reason we decided on using mkpage is that it is much simpler than Jekyll.  We can easily implement improvements and fix bugs quickly.  The biggest benefit is that individuals can control rendering and easily work offline.  While using the Jekyll renderer on GitHub is convenient, it doesn't work with the "make a new branch for changes" approach used to manage lesson content.  When collaborators make a new branch, they have to merge changes back into their personal gh-pages branch for the changes to render.  It can be difficult to determine how new changes from a collaborator will actually look when rendered.  You're also dependent on GitHub's servers, which can be slow to render new changes.  However, if we run into issues with mkpage we can discuss switching back to Jekyll.

**Comment by adam3smith** [comment]
The error triggers on the example content, yes (I've changed one of the lessons, but not the 03 one that triggers the fatal error. -- for whatever reason that's the first one it tries to render )

```
$ mkpage --version
mkpage 1.0.6
```

installed via `npm install mkpage -g` and `npm install mkdoc -g`

**Comment by tmorrell** [comment]
It looks like there is a different mkpage software out there.   @rsdoiel, any thoughts?

Try installing direct from https://github.com/caltechlibrary/mkpage

**Comment by adam3smith** [comment]
that would explain it. I was wondering why you made me go through the not-so-fun experience of working with a nodejs package, which hardly seems easier than using the jekyll ruby gem. 
We'll need to document that in contributing.md then. Will play with this tonight and let you know. Thanks!

**Comment by rsdoiel** [comment]
Yes, the mkpage v1.0.6 escaped into the wild through my foolishness, I would install the most recently release v0.0.16 as a starting point and see of that changes the results. I'll leave these issue open until we get to the bottom of this.,  All the best, Robert

**Comment by adam3smith** [comment]
The way I interpreted this, 
https://github.com/mkdoc/mkpage (which I installed because it does the same thing and was the first mkpage that came up on search)
and 
https://github.com/rsdoiel/mkpage
are completely different projects with, unfortunately, exactly the same name&command. Or am I missing something?

**Comment by rsdoiel** [comment]
mkpage under rsdoiel is where I do prototyping and experiments. You want to
use the one under CaltechLibrary project on github.

Thanks,

Robert

**Comment by tmorrell** [comment]
I've added a note to contributing.md.  We'll consider whether we want to rename mkpage to avoid this clash, and I'll leave this issue open as a record of the potential problem.

**Comment by adam3smith** [comment]
Working for me now that I'm using the correct `mkpage`. Thanks. Leaving the ticket open a discussed above.
